from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from read_files import X,y
from read_files import USERCODE_X
from utils import tokenize_tweet
import numpy as np
import regex as re
from io import StringIO
from sklearn.model_selection import train_test_split
from nltk.tokenize import TweetTokenizer 
from sklearn.metrics import accuracy_score